version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postfb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
